### ISSUE TITLE
Servlet Container 동작 방식에 대한 질문입니다. 동시에 100개 요청이 발생된다면, 몇개의 Thread로 동작할까요?

### ISSUE THREAD

**Issue by flab-true** [f-lab-edu/JimCarry#11]
Servlet Container 동작 방식에 대한 질문입니다. 동시에 100개 요청이 발생된다면, 몇개의 Thread로 동작할까요?

_Originally posted by @flab-true in https://github.com/f-lab-edu/JimCarry/pull/3#discussion_r1779916546_

**Comment by HongSeokWoo1991** [comment]
요청마다 쓰레드를 생성 할 수 있어 100개의 쓰레드를 생성 하지만 쓰레드의 생성 비용은 매우 비싸기 때문에 요청 마다 쓰레드를 생성하면 응답 속도가 느려짐. 그래서 WAS에서는 쓰레드 풀이라는 방식을 사용 하여 미리 쓰레드 풀에 미리 쓰레드를 만들어 놔 요청이 오면 쓰레드 풀에서 하나를 빌려 쓰고 다쓰고 나면 반납하는 방식을 사용.

**Comment by flab-true** [comment]
쓰레드풀의 기본 플로우는 어떻게 구성되어 있을까요? 
100개 요청이 들어오면 쓰레드 풀에서 하나를 빌려서 사용한다고 하셨는데요. 쓰레드 풀보다 많은 요청을 받으면 어떻게 동작하는지 추가 설명을 해주시면 좋겠습니다.
